version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env.docker
    volumes:
      - ./db_backup/operaiq.sql:/docker-entrypoint-initdb.d/operaiq.sql
    networks:
      - red_interna

  web:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - red_interna
    env_file:
      - .env.docker
networks:
  red_interna:
